---
- name: Disks | Set disks fact
  ansible.builtin.set_fact:
    ovirt_disks: "{{ ovirt_vm.disks }}"

- name: Disks | Get disks info
  ovirt.ovirt.ovirt_vm_info:
    auth: "{{ ovirt_auth | mandatory(msg='Authentication required') }}"
    pattern: name={{ ovirt_vm.name }}
    follow: disk_attachments
  register: ovirt_vm_info

- name: Disks | Get disks ID
  ansible.builtin.set_fact:
    ovirt_vm_boot_disk_id: "{{ ovirt_disk.id }}"
  loop: "{{ ovirt_vm_info.ovirt_vms[0].disk_attachments }}"
  loop_control:
    loop_var: ovirt_disk
    label: "{{ ovirt_vm.name }} {{ ovirt_disk.id }}"
  when: ovirt_disk.bootable

- name: Disks | Boot disk
  when: ovirt_vm_boot_disk_id is defined and ovirt_vm_boot_disk_id
  block:
    - name: Disks | Get boot disk state
      ansible.builtin.set_fact:
        ovirt_vm_boot_disk: "{{ ovirt_disk }}"
      loop: "{{ ovirt_vm.disks }}"
      loop_control:
        loop_var: ovirt_disk
        label: "{{ ovirt_vm.name }} {{ ovirt_disk.name }}"
      when: ovirt_disk.bootable is defined and ovirt_disk.bootable

    - name: Disks | Set boot disk state
      ovirt.ovirt.ovirt_disk:
        auth: "{{ ovirt_auth | mandatory(msg='Authentication required') }}"
        vm_name: "{{ ovirt_vm.name | mandatory('VM name required') }}"
        name: "{{ ovirt_vm.name + ovirt_disks_vms_separator + ovirt_vm_boot_disk.name if ovirt_disks_vms_prefix_name
          else ovirt_vm_boot_disk.name | mandatory('Disk name required') }}"
        size: "{{ ovirt_vm_boot_disk.size | mandatory('Disk size required') }}"
        activate: "{{ ovirt_vm_boot_disk.activate | default(true) }}"
        backup: "{{ ovirt_vm_boot_disk.backup | default(omit) }}"
        description: "{{ ovirt_vm_boot_disk.description | default(omit) }}"
        interface: "{{ ovirt_vm_boot_disk.interface | default('virtio_scsi') }}"
        id: "{{ ovirt_vm_boot_disk_id }}"
        pass_discard: "{{ ovirt_vm_boot_disk.pass_discard | default(omit) }}"
        profile: "{{ ovirt_vm_boot_disk.profile | default(omit) }}"
        state: "{{ ovirt_vm_boot_disk.state | default('present') }}"
        wait: "{{ ovirt_disks_wait }}"
        timeout: "{{ ovirt_disks_timeout }}"
        poll_interval: "{{ ovirt_disks_poll_interval }}"
      async: "{{ ovirt_vms_timeout }}"
      poll: 0
      register: ovirt_boot_disk_result

    - name: Disks | Set boot disk result fact
      ansible.builtin.set_fact:
        ovirt_disks_statuses: "{{ ovirt_disks_statuses + [ovirt_boot_disk_result] }}"
      when: ovirt_disks_wait

    - name: Disks | Add a non-boot disks to fact
      ansible.builtin.set_fact:
        ovirt_disks: >-
          {{ (ovirt_disks | rejectattr('bootable', 'defined') | list |
              union(ovirt_disks | selectattr('bootable', 'defined') | rejectattr('bootable', 'equalto', True)) | list) }}

- name: Disks | Set disk state
  ovirt.ovirt.ovirt_disk:
    auth: "{{ ovirt_auth | mandatory(msg='Authentication required') }}"
    vm_name: "{{ ovirt_vm.name | mandatory('VM name required') }}"
    name: "{{ ovirt_vm.name + ovirt_disks_vms_separator + ovirt_disk.name
      if ovirt_disks_vms_prefix_name else ovirt_disk.name | mandatory('Disk name required') }}"
    format: "{{ ovirt_disk.format | default(ovirt_vm.disk_format) | mandatory(msg='Disk type required') }}"
    size: "{{ ovirt_disk.size | mandatory(msg='Disk size required') }}"
    storage_domain: "{{ ovirt_disk.storage_domain | default(ovirt_vm.storage_domain) | mandatory(msg='Disk storage domain required') }}"
    activate: "{{ ovirt_disk.activate | default(true) }}"
    backup: "{{ ovirt_disk.backup | default(omit) }}"
    bootable: "{{ ovirt_disk.bootable | default(omit) }}"
    description: "{{ ovirt_disk.description | default(omit) }}"
    interface: "{{ ovirt_disk.interface | default('virtio_scsi') }}"
    pass_discard: "{{ ovirt_disk.pass_discard | default(omit) }}"
    profile: "{{ ovirt_disk.profile | default(omit) }}"
    read_only: "{{ ovirt_disk.read_only | default(omit) }}"
    shareable: "{{ ovirt_disk.shareable | default(omit) }}"
    wipe_after_delete: "{{ ovirt_disk.wipe_after_delete | default(omit) }}"
    state: "{{ ovirt_disk.state | default('present') }}"
    wait: "{{ ovirt_disks_wait }}"
    timeout: "{{ ovirt_disks_timeout }}"
    poll_interval: "{{ ovirt_disks_poll_interval }}"
  loop: "{{ ovirt_disks }}"
  loop_control:
    loop_var: ovirt_disk
    label: "{{ ovirt_vm.name }} ({{ ovirt_disk.name }})"
  async: "{{ ovirt_vms_timeout }}"
  poll: 0
  register: ovirt_disks_status

- name: Disks | Set disks results fact
  ansible.builtin.set_fact:
    ovirt_disks_statuses: "{{ ovirt_disks_statuses + [ovirt_disk_status] }}"
  loop: "{{ ovirt_disks_status.results }}"
  loop_control:
    loop_var: ovirt_disk_status
  when: ovirt_disks_wait

- name: Disks | Unset facts
  ansible.builtin.set_fact:
    ovirt_disks: ""
    ovirt_vm_boot_disk_id: ""
    ovirt_vm_boot_disk: ""
