---
ovirt_nics_vms: []
# - name: string                   # Name of VM [required]
#   nics:                          # List of nics
#     - interface: string          # Set interface if nic (e1000, pci_passthrough, rtl8139, rtl8139_virtio, spapr_vlan, virtio*)
#       mac_address: string        # Set custom MAC
#       network: string            # Set network [required]
#       network_filter_parameters: # Set network filters
#         - name: string           # Filter name
#           value: string          # Filter value
#       name: string               # Nic name [required]
#       linked: boolean            # Link nic to VM
#       profile: string            # Nic profile

ovirt_nics_wait: true       # Waiting for a response about nics state
ovirt_nics_timeout: 3       # Nics state timeout
ovirt_nics_poll_interval: 1 # Interval for checking nic state
