name: Linter

on: [push]

jobs:
  setup:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Restore cached virtualenv
        uses: actions/cache/restore@v4
        with:
          key: venv-${{ runner.os }}-${{ matrix.python-version }}-linter
          path: .venv
      - name: Upgrade pip and install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip==22.0.2
          pip install \
          ansible-lint==24.12.2 \
          pylint==3.3.3 \
          yamllint==1.35.1
          echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
          echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV
      - name: Saved cached virtualenv
        uses: actions/cache/save@v4
        with:
          key: venv-${{ runner.os }}-${{ matrix.python-version }}-linter
          path: .venv

  pylint:
    needs: setup
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Restore cached virtualenv
        uses: actions/cache/restore@v4
        with:
          key: venv-${{ runner.os }}-${{ matrix.python-version }}-linter
          path: .venv
      - name: Install pip packages
        run: |
          source .venv/bin/activate
          python -m pip install --upgrade pip==22.0.2
          pip install \
          pylint==3.3.3
      - name: Lint the code with pylint
        run: |
          pylint $(git ls-files '*.py')

  yamllint:
    needs: setup
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Restore cached virtualenv
        uses: actions/cache/restore@v4
        with:
          key: venv-${{ runner.os }}-${{ matrix.python-version }}-linter
          path: .venv
      - name: Install pip packages
        run: |
          source .venv/bin/activate
          python -m pip install --upgrade pip==22.0.2
          pip install \
          yamllint==1.35.1
      - name: Lint the code with yamllint
        run: |
          yamllint --format=auto $(git ls-files '*.yml')

  ansible-lint:
    needs: setup
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Restore cached virtualenv
        uses: actions/cache/restore@v4
        with:
          key: venv-${{ runner.os }}-${{ matrix.python-version }}-linter
          path: .venv
      - name: Install pip packages
        run: |
          source .venv/bin/activate
          python -m pip install --upgrade pip==22.0.2
          pip install \
          ansible-lint==24.12.2
      - name: Lint the code with ansible-lint
        run: |
          ansible-lint $(git ls-files '*.yml')
